repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: ruff format .
        language: system
        types: [ python ]

      - id: ruff-lint
        name: ruff-lint
        entry: ruff check .
        language: system
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]

      - id: pip-check
        name: pip-check
        entry: pip check
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy src tests
        language: system
        types: [ python ]
        pass_filenames: false