"""alter table department

Revision ID: 0a6a2f02b8ba
Revises: 3b0fe05fbf4e
Create Date: 2025-04-06 21:41:50.362237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a6a2f02b8ba"
down_revision: Union[str, None] = "3b0fe05fbf4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("department", "parent_id", existing_type=sa.UUID(), nullable=True)
    op.create_index("ix_department_parent_id", "department", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_department_parent_id", table_name="department")
    op.alter_column("department", "parent_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
