"""alter table department

Revision ID: 8cf56b672ac4
Revises: 9fe3e41b620c
Create Date: 2025-04-07 18:12:32.541691

"""

from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cf56b672ac4"
down_revision: Union[str, None] = "9fe3e41b620c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "department",
        sa.Column("head_id", advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_department_head_id_employee"), "department", "employee", ["head_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_department_head_id_employee"), "department", type_="foreignkey")
    op.drop_column("department", "head_id")
    # ### end Alembic commands ###
