"""alter table employee

Revision ID: f033e3e5e21f
Revises: de1925bd6609
Create Date: 2025-04-13 23:43:16.150052

"""

import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f033e3e5e21f"
down_revision: Union[str, None] = "de1925bd6609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def generate_slug(name: str) -> str:
    """Generate a URL-friendly slug from a name."""
    # Remove all non-word characters (except spaces and hyphens)
    slug = re.sub(r"[^\w\s-]", "", name.strip().lower())
    # Replace spaces and hyphens with a single hyphen
    slug = re.sub(r"[-\s]+", "-", slug)
    return slug


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("slug", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    conn = op.get_bind()
    # Get all existing employees
    employees = conn.execute(sa.text("SELECT id, name FROM employee")).fetchall()

    # Generate and update slugs for each employee
    for emp in employees:
        slug = generate_slug(emp.name)
        conn.execute(
            sa.text("UPDATE employee SET slug = :slug WHERE id = :id"), {"slug": slug, "id": emp.id}
        )

    # Make slug column non-nullable and add unique constraint
    op.alter_column("employee", "slug", nullable=False)
    op.create_unique_constraint("uq_employee_slug", "employee", ["slug"])


def downgrade() -> None:
    """Downgrade schema."""
    # Drop unique constraint first
    op.drop_constraint("uq_employee_slug", "employee", type_="unique")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "slug")
    # ### end Alembic commands ###
