"""create employee table

Revision ID: 2e5d9b672e80
Revises: 97e6b5c8831b
Create Date: 2025-04-07 17:47:37.821051

"""

from typing import Sequence, Union

import advanced_alchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e5d9b672e80"
down_revision: Union[str, None] = "97e6b5c8831b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("manager_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["department.id"], name=op.f("fk_employee_department_id_department")
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["employee.id"], name=op.f("fk_employee_manager_id_employee")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee")),
    )
    op.add_column("department", sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True))
    op.add_column(
        "department",
        sa.Column(
            "created_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "department",
        sa.Column(
            "updated_at", advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("department", "updated_at")
    op.drop_column("department", "created_at")
    op.drop_column("department", "sa_orm_sentinel")
    op.drop_table("employee")
    # ### end Alembic commands ###
